In [7]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
slice1 = arr[2:6]
print(slice1)
slice2 = arr[::2]
print(slice2)

[3 4 5 6]
[1 3 5 7 9]


In [8]:
revarr=arr[::-1]
print(revarr)

[9 8 7 6 5 4 3 2 1]


In [5]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12,]])
print(a[0:3:2])
print(a[0::2])
print(a[1::])
print(a[2:2:])
print(a[:2])
print(a[:2:3])

[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[]
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]]


In [26]:
revarr=a[::-1]
print(revarr)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [27]:
col1= a[:,0]
row1=a[0,:]
print(col1)
print(row1)

[1 5 9]
[1 2 3 4]


In [20]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[1])
print(arr[-1])
print(arr[1:4])
print(arr[arr>>25])
print(arr[[1,3]])

10
20
50
[20 30 40]
[10 10 10 10 10]
[20 40]


In [23]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)


[[1 2 5 6]
 [3 4 7 8]]


In [24]:
result1=np.vstack((arr1,arr2))
print(result1)


[[1 2 5 6]
 [3 4 7 8]]


In [25]:
result2=np.dstack((arr1,arr2))
print(result2)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [28]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,0])
print(arr[1,2])

1
6
