In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
import numpy as np
b=np.array ([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
import numpy as np
c=np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
d=np.random.random((3,4))
print(d)

[[0.28117865 0.12715123 0.74474753 0.1037879 ]
 [0.24789605 0.01340924 0.07062909 0.025007  ]
 [0.7078937  0.98550102 0.03778927 0.50512143]]


In [12]:
import numpy as np
e=np.arange (0,20,5)
print(e)

[ 0  5 10 15]


In [8]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[1,2,0,1]])
newarr = arr.reshape(4,3)
print(arr)
print(newarr)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[[1 2 3]
 [4 5 6]
 [7 8 1]
 [2 0 1]]


In [11]:
flat = arr.flatten()
print(arr)
print(flat)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 0 1]]
[1 2 3 4 5 6 7 8 1 2 0 1]


In [15]:
import numpy as np
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

(3, 4)
12
int64
2
